name: "Test"
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:            # For manual runs on branches
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel:
          # With the pinned release.
          - "default"
          # With the latest 26.05 release
          - "cyberus-linux-26.05"
          # With the latest nixos-unstable release
          - "nixos-unstable"
    steps:
      # Avoid: unshare: Operation not permitted
      #
      # This happens when systemd-repart builds images otherwise.
      - name: Disable AppArmor
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Scrounge-up some more space
        uses: samueldr/more-space-action@latest
        with:
          enable-lvm-span: true
          lvm-span-mountpoint: /nix
      - uses: actions/checkout@v5
      - uses: samueldr/lix-gha-installer-action@latest
        with:
          extra_nix_config: |
            keep-env-derivations = true
            keep-outputs = true
            extra-trusted-public-keys = ctrl-os:baPzGxj33zp/P+GAIJXsr8ss9Law+qEEFViX1+flbv8=
            extra-substituters = https://cache.cyberus-linux.com/
      - name: Restore cache
        id: cache
        uses: actions/cache@v5
        with:
          path: .cache
          key: cache-${{ matrix.channel }}-${{ github.ref_name }}-${{ github.run_id }}
          restore-keys: |
            cache-${{ matrix.channel }}-${{ github.ref_name }}-
            cache-${{ matrix.channel }}-
      - name: Repopulate Nix Store
        if: steps.cache.outputs.cache-hit
        run: |
          if [ -d .cache/nix-store ]; then
            # Paths we built in earlier runs are not signed.
            nix path-info --store file://$PWD/.cache/nix-store --all | nix copy --no-check-sigs --from file://$PWD/.cache/nix-store --stdin
          else
            echo No cache to restore.
          fi
      - name: Build the Modules for ${{ matrix.channel }}
        run: |
          set -eux
          if [[ "${{ matrix.channel }}" == cyberus-linux-* ]]; then
              channel=https://channels.cyberus-linux.com/channel/${{ matrix.channel }}.tar.xz
          else
              channel=https://channels.nixos.org/${{ matrix.channel }}/nixexprs.tar.xz
          fi
          nix_args=()

          if [[ "${{ matrix.channel }}" != "default" ]]; then
            nix_args+=(
              --override-input nixpkgs "$channel"
            )
          fi

          nix -L flake check ${nix_args[@]}
      - name: Export Nix Store
        if: always()
        run: |
          mkdir -p .cache/nix-store
          # We never clear paths from the cache. Github will evict the
          # cached file if it is too large (>10GB).
          nix path-info --all | nix copy --to file://$PWD/.cache/nix-store --stdin
